// List of blacklisted domains that should be blocked
export const BLACKLISTED_SITES = [
  // Adult content
  "pornhub.com",
  "xvideos.com",
  "xhamster.com",
  "youporn.com",
  "redtube.com",
  "onlyfans.com",
  "chaturbate.com",
  "livejasmin.com",
  "stripchat.com",
  "cam4.com",
  "brazzers.com",
  "myfreecams.com",
  "flirt4free.com",
  "adultfriendfinder.com",
  "fetlife.com",
  "manyvids.com",
  "clips4sale.com",
  "streamate.com",
  "cams.com",
  "bongacams.com",
  "cam.tv",
  "fancentro.com",
  "fansly.com",
  "justforfans.com",
  "loyalfans.com",
  "modelcentro.com",
  "niteflirt.com",
  "seekingarrangement.com",
  "camcontacts.com",
  "iwantclips.com",
  "jerkmate.com",

  // Gambling
  "bet365.com",
  "pokerstars.com",
  "draftkings.com",
  "fanduel.com",
  "bovada.lv",
  "betway.com",
  "888casino.com",
  "williamhill.com",
  "unibet.com",
  "bwin.com",
  "sportbet.com",
  "stake.com",

  // Malicious/Phishing
  "phishing-netflix.com",
  "paypal-secure-login.com",
  "amazon-account-verify.net",
  "facebook-security-login.com",
  "google-docs-share.com",
  "microsoft365-login.net",
  "apple-id-verify.com",
  "verify-wellsfargo.com",
  "chase-secure-login.net",
  "coinbase-wallet-verify.com",

  // Hate/Extremist Content
  "stormfront.org",
  "dailystormer.su",
  "8kun.top",
  "gab.com",
  "parler.com",
  "4chan.org",
  "kiwifarms.net",
  "bitchute.com",
  "infowars.com",
  "breitbart.com",

  // Known malware distribution
  "downloadfreeramhere.com",
  "crackfullversion.com",
  "freemoviedownload.net",
  "piratebay-proxy.com",
  "crackingpatching.com",
  "cracksurl.com",
  "serialkey.org",
  "keygenpro.net",
  "warez-bb.org",
  "torrentfreak.net",
  "piratebay.org",

  // Scam/Fraud sites
  "nigerian-prince-fortune.com",
  "crypto-investment-returns.net",
  "make-money-fast.biz",
  "binary-options-profit.com",
  "forex-guaranteed-profits.com",

  // Dangerous supplements/drugs
  "buy-steroids-online.net",
  "research-chemicals-shop.com",
  "legal-highs-store.com",
  "prescription-meds-online.com",
  "underground-pharmacy.net",

  // URL Shorteners/Redirectors
  "bit.ly",
  "tinyurl.com",
  "goo.gl",
  "ow.ly",
  "t.co",
  "is.gd",
  "buff.ly",
  "adf.ly",
  "tiny.cc",
  "cutt.ly",
  "shorturl.at",
  "rebrand.ly",
  "snip.ly",
  "bl.ink",
  "clck.ru",
  "short.io",
  "s2r.co",
  "v.gd",
  "soo.gd",
  "dai.ly",

  // IP grabbers/loggers
  "grabify.link",
  "grabify.icu",
  "grabify.me",
  "grabify.world",
  "grabify.gg",
  "grabify.org",
  "grabify.lol",
  "grabify.xyz",
  "grabify.club",
  "grabify.live",
  // IP grabbers/loggers (continued)
  "location.cyou",
  "mymap.icu",
  "mymap.quest",
  "mapss.icu",
  "map-s.online",
  "crypto-o.click",
  "cryp-o.online",
  "customer.autos",
  "account.beauty",
  "bank.charity",
  "photospace.life",
  "mymassive.pics",
  "photovault.store",
  "imagehub.fun",
  "picturestash.mom",
  "clickthis.photo",
  "sharevault.cloud",
  "picshare.mom",
  "picshare.hair",
  "imagestash.pics",
  "xtube.chat",
  "myprivate.yachts",
  "screensnaps.top",
  "customersupport.click",
  "mypicparade.pics",
  "imagevault.cloud",
  "photovault.pics",
  "foot.wiki",
  "gamergirl.pro",
  "picshost.pics",
  "pichost.pics",
  "imghost.pics",
  "screenshare.pics",
  "myprivate.pics",
  "shrekis.life",
  "screenshot.best",
  "gamingfun.me",
  "stopify.co",
];
